### ISSUE TITLE
[dependencies]: infospect and share_plus versions conflict

### ISSUE THREAD

**Issue by DaniilPavlov** [kushalmahapatro/infospect#8]
**Describe the bug**
I need to update share_plus package in my project from 7.2.1 version to 10.0.1, but following problem occurs:

flutter pub get --no-example
Resolving dependencies...
Because infospect 0.1.3 depends on share_plus ^7.2.1 and no versions of infospect match >0.1.3 <0.2.0, infospect ^0.1.3 requires share_plus ^7.2.1.
So, because depends on both share_plus ^10.0.1 and infospect ^0.1.3, version solving failed.

**To Reproduce**
1. Go to pubspec.yaml
2. Set share_plus version to 10.0.1
3. Set infospect version to 0.1.3
4. Run pub get

**Expected behavior**
Project compiles.

Please update share_plus version.

**Comment by kushalmahapatro** [comment]
Hi @DaniilPavlov,

Thanks for creating the issue. 
I have updated the share_plus version to 10.0.1, and it's available in the latest version of `Infospect - 0.1.4`.

Please have a look and let me know if that solves your problem.

**Comment by DaniilPavlov** [comment]
@kushalmahapatro all good, thank you!
